name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-artifacts-macos:
    name: "run Macos Binaries"
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
      - name: test binary
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download static-libiconv-macos -p 'rylm1c1hdafrph6rfxjfgmlpwssi3sr1-nickel' -D bin
          chmod +x ./bin/rylm1c1hdafrph6rfxjfgmlpwssi3sr1-nickel
          ./bin/rylm1c1hdafrph6rfxjfgmlpwssi3sr1-nickel --help
