name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-artifacts-macos:
    name: "run Macos Binaries"
    runs-on: macos-15
    steps:
      - name: test binary
        run: |
          gh release download static-libiconv-macos -p 'nickel' -D bin
          chmod + x ./bin
          ./bin/nickel
